### ISSUE TITLE
add header guards to all .h files?

### ISSUE THREAD

**Issue by greg-minshall** [glouw/ctl#21]
hi.  some files (ctl/str.h, ctl/ctl.h) have header guards
````
#ifndef __CTL_H__
#define __CTL_H__
...
#endif /* ndef __CTL_H__ */
````
(where the comment on the `#endif` line is my style.)

maybe it would be a good idea to add such to all the .h files.

also, maybe, e.g., `s/\b__STR_H_/__CTL_STR_H__/`, just to try to avoid any future name collisions?

**Comment by glouw** [comment]
Not a bad idea, let me look into it

**Comment by greg-minshall** [comment]
apologies.  in fact, afaict, all the ones *not* guarded *can* be `#included` multiple times, each with a different `T` defined.

**Comment by glouw** [comment]
Yes that's the idea, as the crux of CTL is just boilerplate reduction by abusing #include and redefining T. Considering <str.h> is not polymorphic (it's really just an extension of vector with T defined as char) and <ctl.h> being the base header with some nice to use macros like foreach and swap, everything else is the hands of the programmer to include as many times as they like. You can even build containers of containers. If I remember the syntax (it's been a year since I've touched CTL) you can do something like:

```
#define P
#define T int
#include <vec.h>

#define T vec_int 
#include <lst.h> // gives us a list of int vectors (lst_vec_int) where the constructors and destructors are magically inherited from vec_int.

#define T lst_vec_int
#include <deq.h> // gives us a deque of list of int vectors (deq_lst_vec_int)... and forever on and so on
```

YMMV. It's a very powerful tool; great for embedded systems without runtime support for the STL. It's also highly performant (I got to about 80-90% of the speed of the STL on average I think for all containers). It was a thought experiment, and I'm glad there are some people out there using it for production grade stuff.

As an aside, I've recently been playing with void pointers, and I've built my own programming language with it. As cool as C is, and the 10 something years I've spend with it, I've learned that C is best used building tools to get yourself away from C. I'm building my own programming language, I mean: https://github.com/glouw/rr

Excuse the shameless plug :P

**Comment by greg-minshall** [comment]
yeah -- that's certainly my use, and i'm very happy with it.  thanks for doing it.  good luck with Roman II!
